#!/bin/sh

set -e

case "$1" in
  purge)
    if [ -d /var/lib/feedsd ]; then
      rm -rf /var/lib/feedsd
    fi
    if [ -d /var/log/feedsd ]; then
      rm -rf /var/log/feedsd
    fi
    if [ -d /etc/feedsd ]; then
      rm -rf /etc/feedsd
    fi
  ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d feedsd remove >/dev/null
fi

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask feedsd.service >/dev/null
	fi
  if [ -e /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    db_purge
  fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge feedsd.service >/dev/null
		deb-systemd-helper unmask feedsd.service >/dev/null
	fi
fi
# End automatically added section

