#!/bin/sh

set -e

test $DEBIAN_SCRIPT_DEBUG && set -v -x

chperms() {
	# chperms <user> <group> <perms> <file>
	if ! OVERRIDE=`dpkg-statoverride --list $4 2>&1`; then
		if [ -e $4 ]; then
			chown -R $1:$2 $4
			chmod -R $3 $4
		fi
	fi
}

case "$1" in
  configure)
    if ! getent passwd feedsd > /dev/null; then
        adduser --system \
                --quiet \
                --group \
                --no-create-home \
                --disabled-password \
                --home /var/lib/feedsd \
                feedsd
    fi

    if [ ! -d /var/lib/feedsd ]; then
        mkdir /var/lib/feedsd
    fi

    FEEDSD_VERSION=$(dpkg -s $DPKG_MAINTSCRIPT_PACKAGE | sed -n 's/^Version: //p')
    rm -rf /var/lib/feedsd/runtime/current
    ln -sf "$FEEDSD_VERSION" /var/lib/feedsd/runtime/current
    if [ -e "/etc/feedsd" ]; then
        rm -r /var/lib/feedsd/runtime/current/etc/feedsd
        mv "/etc/feedsd" /var/lib/feedsd/runtime/current/etc/feedsd
    fi

    chperms feedsd feedsd 0775 /var/lib/feedsd
  ;;
  configure)
esac

# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask feedsd.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled feedsd.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable feedsd.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state feedsd.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/feedsd" ]; then
		update-rc.d feedsd defaults >/dev/null
		invoke-rc.d feedsd start || exit $?
	fi
fi
# End automatically added section

exit 0;
