#!/bin/sh

set -e

case "$1" in
  purge)
    if [ -d /var/lib/ela-feedsd ]; then
      rm -rf /var/lib/ela-feedsd
    fi
    if [ -d /var/log/ela-feedsd ]; then
      rm -rf /var/log/ela-feedsd
    fi
    if [ -d /etc/ela-feedsd ]; then
      rm -rf /etc/ela-feedsd
    fi
  ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d ela-feedsd remove >/dev/null
fi

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask ela-feedsd.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge ela-feedsd.service >/dev/null
		deb-systemd-helper unmask ela-feedsd.service >/dev/null
	fi
fi
# End automatically added section

