#!/bin/sh

set -e

test $DEBIAN_SCRIPT_DEBUG && set -v -x

chperms() {
	# chperms <user> <group> <perms> <file>
	if ! OVERRIDE=`dpkg-statoverride --list $4 2>&1`; then
		if [ -e $4 ]; then
			chown $1:$2 $4
			chmod $3 $4
		fi
	fi
}

case "$1" in
  configure)
    if ! getent passwd ela-feedsd > /dev/null; then
        adduser --system \
                --quiet \
                --group \
                --no-create-home \
                --disabled-password \
                --home /var/lib/ela-feedsd \
                ela-feedsd
    fi

    if [ ! -d /var/lib/ela-feedsd ]; then
        mkdir /var/lib/ela-feedsd
    fi

    if [ ! -d /var/log/ela-feedsd ]; then
        mkdir /var/log/ela-feedsd
    fi

    chperms ela-feedsd ela-feedsd 0775 /var/lib/ela-feedsd

    chperms ela-feedsd ela-feedsd 0775 /var/log/ela-feedsd
  ;;
esac

# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask ela-feedsd.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled ela-feedsd.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable ela-feedsd.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state ela-feedsd.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/ela-feedsd" ]; then
		update-rc.d ela-feedsd defaults >/dev/null
		invoke-rc.d ela-feedsd start || exit $?
	fi
fi
# End automatically added section

exit 0;
