#!/bin/sh

set -e

. /usr/share/debconf/confmodule

case "$1" in
  upgrade|install)
    db_get rcdiscover/rpfilter || true
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

exit 0
