#!/bin/sh

set -e

. /usr/share/debconf/confmodule

case "$1" in
  configure)
    db_get feedsd/agreement || true
    if [ "$RET" != "true" ]; then
      if [ "$RET" != "false" ]; then
        echo "Failed to ensure feedsd agreement, error($RET)" >&2
      fi
      exit 1
    fi
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

exit 0
