#!/bin/sh

set -e

. /usr/share/debconf/confmodule

case "$1" in
  upgrade|install)
    db_get feedsd/agreement || true
    AGREE=$RET 
    db_purge
    if [ "$AGREE" != "true" ]; then
      if [ "$AGREE" != "false" ]; then
        echo "Failed to ensure feedsd agreement, error($AGREE)" >&2
      fi
      exit 1
    fi
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

exit 0
