#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/feedsd" ]; then
	invoke-rc.d feedsd stop || exit $?
fi

if [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi

# End automatically added section
